create extension if not exists pgcrypto;

create table if not exists public.djob_public_jobs (
  id bigint generated by default as identity primary key,
  uuid text unique,
  job_number text not null unique,
  job_source text,
  title text,
  description text,
  is_hot boolean not null default false,
  is_sticky boolean not null default false,
  is_quick_apply boolean not null default false,
  show_updated_date boolean not null default true,
  embedding_statements text,
  position_id text unique,
  category text,
  location text,
  job_type text,
  job_role text,
  scope text,
  publish_date timestamptz,
  position_status text,
  internal_salary text,
  screening_questions text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.djob_public_jobs
  add column if not exists job_source text;

create index if not exists idx_djob_public_jobs_updated_at
  on public.djob_public_jobs (updated_at desc);

create index if not exists idx_djob_public_jobs_source_updated_at
  on public.djob_public_jobs (job_source, updated_at desc);

create index if not exists idx_djob_public_jobs_position_status
  on public.djob_public_jobs (position_status);

create table if not exists public.djob_public_applications (
  id bigint generated by default as identity primary key,
  application_uuid uuid not null unique default gen_random_uuid(),
  job_uuid text,
  job_number text not null,
  position_id text,
  full_name text not null,
  email text not null,
  phone text not null,
  screening_answers text,
  cv_original_name text,
  cv_file_path text,
  cv_file_type text,
  noresume boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_djob_public_applications_created_at
  on public.djob_public_applications (created_at desc);

create index if not exists idx_djob_public_applications_job_number
  on public.djob_public_applications (job_number);

create index if not exists idx_djob_public_applications_cv_path
  on public.djob_public_applications (cv_file_path);

alter table public.djob_public_jobs enable row level security;
alter table public.djob_public_applications enable row level security;
